site_name: Geoff Schrecker's Website
theme:
  name: material
nav:
  - Home: index.md
  - Family History:
      - U3A Family History: family_history.md
      - Royal Inniskilling Fusiliers: Inniskillings.md
  - Walks:
      - Grindleford to Froggatt Loop: Grindleford1.md
  - MkDocs: mkdocs.md

markdown_extensions:
  - attr_list
  - md_in_html
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
